version: '3.9'

services:
  bd:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    env_file:
      - .env/db
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/database_creation.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  api:
    image: python:3.13
    container_name: fastapi
    working_dir: /opt/api
    command: bash -c "pip install pdm && pdm install && pdm run api --host 0.0.0.0"
    volumes:
      - ./api:/opt/api
    depends_on:
      - bd
    ports:
      - "8000:8000"
    env_file:
      - .env/api
      - .env/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
