version: '3.9'

services:
  bd:
    image: mariadb:11.3
    container_name: networkers-db
    restart: always
    env_file:
      - .env/db
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/database_creation.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  api:
    image: python:3.13
    container_name: networkers-api
    working_dir: /opt/api
    command: bash -c "pip install pdm && pdm install && pdm run api --host 0.0.0.0"
    volumes:
      - ./api:/opt/api
    depends_on:
      - bd
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env/api
      - .env/db
      - .env/common
    networks:
      - app-network
  
  web:
    image: node:23.0
    container_name: networkers-web
    working_dir: /opt/web
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./front-js:/opt/web
    depends_on:
      - api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env/common
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
